Closes #28  UI ist nun Responsive. Wichtig! Nicht fertigstellen bevor der "Geisterbewegung" PR fertiggestellt wurde!
hauertmann-it-consulting/hackman pull request #39
Opened 2021-07-29 13:58 UTC by AndreDelfs97

**Wichtig**
Der PR Geisterbewegung muss vorher fertiggestellt werden

Das Spielfeld wurde nun Responsive entworfen.
An das Resize Event vom Window wurde eine js Methode gebunden welche die Werte berechnet und per CSS Injection anpasst.
Dies passiert so da man im CSS nicht die Werte eines Attributes auf die eines anderen Attributes setzen kann.
Bei der Statistik kommen simple Media Querys zum Einsatz.

Ausserdem wurde die Ordnerstruktur verbessert/sortiert.

2021-08-02 07:44 UTC, felixhartmann00 commented on src/Components/GameFieldComponent/GhostComponents/Ghost1.tsx
> +const Ghost1: React.FC<any> = () => {
Warum vier exakt gleiche Ghosts ?

2021-08-02 08:45 UTC, felixhartmann00 requested changes

2021-08-02 08:45 UTC, felixhartmann00 commented on src/Types/Character/GhostCharacter.ts
> +
Wenn der Hackman als Character instanziiert wird kann der Ghost nicht vom Character der Erben. Das bedingt Hackman == Ghost und das ist nicht der Fall.

2021-08-03 07:23 UTC, MauriceEberle approved these changes

2021-08-03 10:11 UTC, merged