Feature/schmalere Wände
hauertmann-it-consulting/hackman pull request #5
Opened 2021-03-26 15:09 UTC by AndreDelfs97

Es wurden Vertikale sowie Horizontale Wände hinzugefügt

2021-03-30 07:42 UTC, klifrieri requested changes

2021-03-30 07:42 UTC, klifrieri commented on src/App.tsx
> +  [Wall, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Wall],
Was bedeuten die Wörter Vell, Holl und Empty auf Deutsch? :-)

2021-03-30 07:42 UTC, klifrieri commented on src/index.css
> +} */
Ist das kommentiert?

2021-03-30 07:45 UTC, AndreDelfs97 commented on src/index.css
> +} */
Ja, in CSS Files kann man mithilfe von /* und */ einen Block von Code auskommentieren.

2021-03-30 07:45 UTC, klifrieri requested changes

2021-03-30 07:45 UTC, klifrieri commented on src/App.tsx
> +  [Wall, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Wall]
Was bedeutet Empy?

2021-03-30 07:46 UTC, klifrieri commented on src/index.css
> +} */
Ja aber brauchen wir es?

2021-04-13 13:11 UTC, felixhartmann00 commented on src/App.tsx
> +  [Wall, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Holl, Wall]
Benennungen der Spielfeldelemente ist in der App.tsx auf 4 Buchstaben gekürzt worden um die Lesbarkeit und das arbeiten im Array zu erleichtern.

2021-04-13 13:18 UTC, felixhartmann00 commented on src/index.css
> +} */
ist mit den neuen commit rausgeflogen

2021-04-13 13:21 UTC, klifrieri commented on src/App.tsx
> +  [Empy, Empy, Coin, Vell, Coin, Vell, Vell, Coin, Vell, Empy, Empy, Empy, Vell, Coin, Vell, Vell, Coin, Vell, Coin, Empy, Empy],
Was bedeutet Empy? Oder ist das nur, damit alles gleich lang ist?

2021-04-13 13:28 UTC, felixhartmann00 commented on src/App.tsx
> +  [Empy, Empy, Coin, Vell, Coin, Vell, Vell, Coin, Vell, Empy, Empy, Empy, Vell, Coin, Vell, Vell, Coin, Vell, Coin, Empy, Empy],
#

> Benennungen der Spielfeldelemente ist in der App.tsx auf 4 Buchstaben gekürzt worden um die Lesbarkeit und das Arbeiten im Array zu erleichtern.

2021-04-14 07:59 UTC, klifrieri commented on src/App.tsx
> +  [Empy, Empy, Coin, Vell, Coin, Vell, Vell, Coin, Vell, Empy, Empy, Empy, Vell, Coin, Vell, Vell, Coin, Vell, Coin, Empy, Empy],
Ich denke, wir brauchen da brauchen wir eine andere Lösung.

2021-04-23 07:21 UTC, klifrieri commented on src/App.tsx
> +import Empy from "./Components/Empty";
Wird das benutzt?

2021-04-23 07:22 UTC, klifrieri commented on src/App.tsx
>  import Wall from "./Components/Wall";
Wird der Import benutzt?

2021-04-23 07:38 UTC, felixhartmann00 commented on src/App.tsx
>  import Wall from "./Components/Wall";
das empy wird noch benutzt das andere ist entfernt worden

2021-04-23 07:51 UTC, merged